[package]
name = "collateral-repro"
version = "0.1.0"
edition = "2018"
license = "MIT"
publish = false

[dependencies]
arrayref = "0.3.6"
num-derive = "0.3"
num-traits = "0.2"
solana-program = "1.5.0"
spl-token = {version = "3.0.1", features = ["no-entrypoint"]}
thiserror = "1.0.21"

[features]
test-bpf = []

[dev-dependencies]
assert_matches = "1.4.0"
solana-program-test = "1.5.0"
solana-sdk = "1.5.0"
solana-validator = "1.5.0"
tokio = { version = "0.3", features = ["macros"]}

[lib]
crate-type = ["cdylib", "lib"]